### ISSUE TITLE
Enable grafana alerting

### ISSUE THREAD

**Issue by klu03rl** [algenty/grafana-flowcharting#127]
Enhancement request - 
Implement integration with Grafana's alerting module within a plugin.

Rationale: flowcharting is great for creating dashboards, but when developing many it is not possible to monitor all of them all the to e manually and action accordingly. Additional functionality is needed to be able to alert on threshold breeches from the flowcharting plugin. Suggestion would be to integrate grafana's alerting capability into flowcharting. Work around has been to duplicate the flowcharting panel, convert to plugin like graph and create a "ghost" panel to make use of the alerting functionality but this is not ideal.
Using Grafana's alerting would also allow use of webhook to push flowcharting data to collaboration tools like Slack or MS Teams.

Great continued work Arnaud!
How does / can the flowcharting community help you developing the plugin seems you are doing it single handedly?

**Comment by algenty** [comment]
Thx for your comment,
Community can help by pull request by i need to fix rules before

**Comment by bijwaard** [comment]
In my view alerting could be seen a higher level feature and would therefore make more sense at the dashboard level instead of per panel. On a similar note it makes sense to me to have the ability to define measurement [queries at the dashboard level](https://github.com/grafana/grafana/issues/7360) instead of within every panel / plugin. This would streamline a lot of sensor invocations that may now be done multiple times.

**Comment by klu03rl** [comment]
Hi bijwaard,

I think definition at a panel level rather than dashboard level is more of a design principle of grafana rather than than something that could easily be implemented into flowCharting. I believe this is so that dashboards can easily contain multiple panels from different sources with different visualisation.

**Comment by klu03rl** [comment]
Oops didn't mean to close...

**Comment by bijwaard** [comment]
Hi Kul3rl,
I agree having rules and alerts at dashboard level is more a grafana design issue, that's why I put my thumb up for the relevant grafana ticket mentioned above. At the moment there can be quite some repetition of queries in the different panels, that won't be perfectly aligned in time as they are executed after one another and won't be as bandwidth/performance efficient as they could be when combined.

At the moment it seems that alerts are only integrated in graph panels. If you could define them at dashboard level based on dashboard measurements, you would also be able to use the alert results in any panel.

Kind regards,
Dennis

**Comment by bijwaard** [comment]
Hi,
We seem to have reusable queries now [in grafana 7.00](https://grafana.com/docs/grafana/latest/guides/whats-new-in-v7-0/#transformations), that could work as well to have the alerts in one of the panels, and hopefully get rid of redundant queries.
Kind regards,
Dennis

**Comment by algenty** [comment]
You can also in V6, In query, choose dashboard datasource

**Comment by xkilian** [comment]
If you are using Prometheus for your alerts, you can use the ALERTS{alertname=~"blah.*"} metric, which is a metric about the current active alerts.
