### ISSUE TITLE
Structured rules framework

### ISSUE THREAD

**Issue by klu03rl** [algenty/grafana-flowcharting#132]
Hi Arnaud

It would be great for Flowcharting to have the ability to structure rules in a parent / child approach. This would make it easier to have levels of reporting e.g i.e how to report a high level failure of something e.g. a business service if one of many monitored lower level metrics reaches a threshold e.g high CPU / process failure etc.
Sorry not tried 0.7.x yet if some capability is implemented in new rules approach.

**Comment by algenty** [comment]
If you read Gettting started, you can see when object (mapping) is used in multi rule, it take the hightest level even in 0.6.1.
https://algenty.github.io/flowcharting-repository/STARTED.html

**Comment by klu03rl** [comment]
Thanks Arnaud, got it.

Reading the documentation the header takes the state of whichever child rule for value mapping is defined first with one grafana panel.

As our dashboards are getting more complex we are starting to break out the levels of detail and abstraction into different panels but linking them though hyperlinks so that someone can click though the hyper links up and down the levels.
This then becomes more challenging for the higher level view to get an aggregated status of the child metrics in other panels. Do you see this is possible in any way? It would need a rule to be based on the outcome of another rule in another panel I would think..

Richard

**Comment by xkilian** [comment]
What you are asking should really be done elsewhere, such as in a recording_rule in Prometheus or other system (grafana alarm state?) which would handle the business logic of parent/child , software/hardware dependencies or any other calculated outcome.

Hope this helps. :-)

**Comment by klu03rl** [comment]
Thanks xkilian

For Prometheus data source metrics we can, our InfluxDb, I don't think there's an equivalent solution. 
Yes would be good to do within grafana alert, unfortunately defining alerts isn't possible with Flowcharting at the moment, I had raised an enhancement idea for this also.

**Comment by xkilian** [comment]
The important thing is that this state can be associated with the metric, which is why I mentionned a recording rule. If an Alert can be considered a metric and can be queried and displayed, than that is good also. Sometimes Alerts (in certain systems) are not real metrics and cannot be queried if they are not in alert state (Ex. Prometheus and I think Grafana Alerts too)
I personnaly do not think that creating alerts that are linked to grafana is a high priority, they can be defined elsewhere and also better managed elsewhere (Cortex, Prometheus/Karma, Influx, etc.). 
Cheers,
