### ISSUE TITLE
Documentation for gradient mode

### ISSUE THREAD

**Issue by xkilian** [algenty/grafana-flowcharting#142]
flowcharting 0.7
I have tried to get the gradient mode to work and failed. Is the feature functional with 0.7?
The documentation does not provide a clear example of how to configure it. Please provide more extensive documentation for configuring it correctly and how it functions (limitations, gotchas, etc.)

**Comment by algenty** [comment]
Hi xkilian
I need to update doc, i know, here, an example (i need help for it)
![image](https://user-images.githubusercontent.com/47012725/78942739-95907700-7aba-11ea-8a51-c918d21115ba.png)
In this example, we have 3 colors (red, yellow and green ) but only 2 values,
1) If the value is under 40, your shape is alway RED without gradient because flowcharting don't know the radio between red and yellow ( ? < value > 40)
2) If the value is between 40 and 80, flowcharting calculate the ratio with this formule : 
(Curr_value - begin_color_value)/(end_color_value - begin_color_value)
Example, for 60 : 
(60 - 40)/(80 - 40) = 0.5
Flowcharting calculate color between yellow and red with 0.5 (middle).
3) If color is above 80, color is alway red (80 < value> ?)
To solve the problem, you need to define the red value like this : 
![image](https://user-images.githubusercontent.com/47012725/78943934-1badbd00-7abd-11ea-8acb-55534dbce61a.png)

I hode i'am clear,
You can found a big example with floorplan dashboard here : 
 https://play.grafana.org/d/Unu5JcjWk/flowcharting-index?orgId=1

See you later,
Arnaud

**Comment by xkilian** [comment]
Ah. Much clearer. Thank you for taking the time to explain it. I can now get it to display correctly temperature changes for bandwidth. :-)
For things that have high variability like bandwidth, cpu, # of transactions versus saturation it is very nice.

**Comment by algenty** [comment]
your're welcome
