### ISSUE TITLE
Feature Request - Support sparklines instead of graphs

### ISSUE THREAD

**Issue by xkilian** [algenty/grafana-flowcharting#167]
Create an additionna Tooltip metric output mode that would  be same as text (no graph) but adds a sparkline. if supported by chartist.
The reason this is interesting is to make more metrics fit in tooltips while still retaining some indication of historical trend.

**Comment by algenty** [comment]
https://codepen.io/jonwilkinson/pen/grEjYY?__cf_chl_jschl_tk__=c270388d05fda2bdd0ca2805d29005517a13fcb4-1589954073-0-AW6fN5Nf0oB2y0mjOh_zQJbmcur_JrgXA3wiYT0hDyJ7_Ji-NUBNxRPTptleedBrWSpdFCOXSQNZGg9mxSTVmRziGMtSXBpY2CAuslFcU3Nyne5hpFolrxEUjetpOgpeKfsIOnMGmeLtMkVpBkQssZa9Vj-B_VaHWhheNo5ULtalz0YN5JWhjo4Oy2IwBqPuUvR9M-20gJ2r0zwTtd0eqNggjqK-Jg-GWSQqg-d0fHt9VtlGPtKWmiboRKl4boC62asm7hxNoxGmYVGh8zPK7-x4AgSctC7Hbx15DoKfbYRkP1mRI2oXmHhL0x0mdQGMlayE79tHJr27MARZJVDiCOkcrebd1g7skXDsxX-hBaIs

**Comment by xkilian** [comment]
Ah. Good stuff.

**Comment by CrashLaker** [comment]
Btw.. Idk if we can increment this thread or we should discuss this on a new one instead.
I'm trying to embed a line chart (sparkline-ish) to the board.
The result I'm expecting to have is something like this from ELK Canvas:
![image](https://user-images.githubusercontent.com/4432491/82467190-c4c1dd00-9a97-11ea-84b8-f465639d35ee.png)

I tried doing some tests using Grafana's `Share Image` option and embedding it directly to Draw.io then having it refreshed using Flowcharting's `Change URI` mapping rule
![image](https://user-images.githubusercontent.com/4432491/82467703-55002200-9a98-11ea-8308-caea3efecda2.png)

The problem is.. With this approach I lose the animation and the process of fetching a new image is rather slow and the image just blinks when it gets updated.
besides the image gets stretched and completely loses quality
![flowcharting-embedimage](https://user-images.githubusercontent.com/4432491/82468223-ecfe0b80-9a98-11ea-82eb-3c5cbe2c858f.gif)

any ideas?

**Comment by CrashLaker** [comment]
this might help
https://drawio-app.com/curved-connectors-in-draw-io-diagrams/
![image](https://user-images.githubusercontent.com/4432491/82519624-7bee4080-9af8-11ea-88d2-f598d53de2ae.png)
```
<mxCell id="ou_lJY5d8GHdEjfPY0aJ-2" value="" style="curved=1;endArrow=classic;html=1;" edge="1" parent="1">
  <mxGeometry width="50" height="50" relative="1" as="geometry">
	<mxPoint x="80" y="270" as="sourcePoint" />
	<mxPoint x="700" y="270" as="targetPoint" />
	<Array as="points">
	  <mxPoint x="150" y="220" />
	  <mxPoint x="270" y="310" />
	  <mxPoint x="340" y="210" />
	  <mxPoint x="410" y="330" />
	  <mxPoint x="460" y="230" />
	  <mxPoint x="550" y="350" />
	  <mxPoint x="570" y="230" />
	</Array>
  </mxGeometry>
</mxCell>
```

**Comment by algenty** [comment]
in roadmap

**Comment by algenty** [comment]
Very nice


Le mar. 11 mai 2021 à 17:15, Carlos Aguni • 顾宁 ***@***.***> a
écrit :
