### ISSUE TITLE
Solarwinds Datasource Mapping Metrics "undefined"

### ISSUE THREAD

**Issue by fabiokoya** [algenty/grafana-flowcharting#192]
Hi, I`m trying to use flowcharting 0.9.0 with Solarwinds Orion Datasource in Grafana 7.0.3 . 
But when I add the query there is no Alias option,  and when I add the querie I can see the Metrics and the Column field in the Mapping section,  but the metrics only options are "undefined". 
![flowchart](https://user-images.githubusercontent.com/66443694/84842973-7b639f80-affb-11ea-8a6a-33be683c2c3d.png)

I can select undefined, and select the Column.  It works while I`m editing, but once I click save or apply all my changes get deleted, I`m assuming this issue is related to the undefined in the metric. 
Is there any way to add a name to this metric field from the Solawinds Query?

**Comment by algenty** [comment]
need investigation

**Comment by CrashLaker** [comment]
It looks like from the doc [here](https://github.com/etichy/grafana-swis-datasource) that you must have at least two columns. One being the time and other the alias(es).

```sql
SELECT
     downsample(ObservationTimeStamp) as time,
     a.Node.Caption,
     AVG(AvgLoad) as CpuLoad,
     AVG(AvgMemoryUsed) as MemoryUsed
FROM Orion.CPULoad a
WHERE ObservationTimeStamp BETWEEN $from AND $to
GROUP BY downsample(ObservationTimeStamp), a.Node.Caption, a.NodeID
ORDER BY time DESC
```

My guess is instead of formatting the query result like this:
| Caption   | Status   |
|:----------|:---------|
| Switch0   | DOWN     |
| Switch1   | UP       |
| Switch2   | UP       |
| Switch3   | UP       |
| Switch4   | DOWN     |
| Switch5   | UP       |
| Switch6   | DOWN     |
| Switch7   | DOWN     |
| Switch8   | DOWN     |
| Switch9   | DOWN     |

you need to have something like this

| time                | Switch0   | Switch1   | Switch2   | Switch3   | Switch4   |
|:--------------------|:----------|:----------|:----------|:----------|:----------|
| 2020-06-17 00:00:00 | UP        | DOWN      | DOWN      | DOWN      | UP        |
| 2020-06-17 01:00:00 | DOWN      | DOWN      | DOWN      | DOWN      | DOWN      |
| 2020-06-17 02:00:00 | DOWN      | DOWN      | DOWN      | UP        | UP        |
| 2020-06-17 03:00:00 | UP        | DOWN      | DOWN      | DOWN      | DOWN      |
| 2020-06-17 04:00:00 | UP        | UP        | UP        | UP        | UP        |
| 2020-06-17 05:00:00 | UP        | UP        | UP        | DOWN      | DOWN      |
| 2020-06-17 06:00:00 | DOWN      | UP        | DOWN      | DOWN      | DOWN      |
| 2020-06-17 07:00:00 | DOWN      | UP        | DOWN      | UP        | UP        |
| 2020-06-17 08:00:00 | DOWN      | DOWN      | DOWN      | DOWN      | UP        |
| 2020-06-17 09:00:00 | UP        | DOWN      | DOWN      | DOWN      | UP        |

or separate them by queries

**Comment by fabiokoya** [comment]
Thank You for the support, Now it`s working, I create a new panel from scratch, and changed it to TIme Series and add the TIme in the query like : 
SELECT GETDATE() as Time, Caption , Status as metric
FROM Orion.Nodes
where Caption =  'XXXXX' 

After that, The Field Column disappeared, leaving only "Apply to Metrics" with the correct Caption field from my query.
