### ISSUE TITLE
svg exported from cloudcraft are only one object

### ISSUE THREAD

**Issue by kyrianae** [algenty/grafana-flowcharting#231]
I m trying to use a svg export from cloudcraft
Only one item is found when i want to bind with values

draw io is not able to ungroup this svg , but inkscape can afetr edition the svg doesn t look realy good

is there a way on svg load in flowcharting to show the hierarchy tree of svg to select nodes ?

**Comment by kyrianae** [comment]
[cloudcraft.zip](https://github.com/algenty/grafana-flowcharting/files/5395208/cloudcraft.zip)
here is a cloudcraft export

**Comment by algenty** [comment]
Try to post your question on draw.io support, you need to convert it in xml drawio format.
https://groups.google.com/forum/#!forum/drawio

BR
Arnaud

**Comment by kyrianae** [comment]
done 

thanks for your help

**Comment by kyrianae** [comment]
answer from drawio
drawio is not a svg editor ...

how to solve the problem 

I didn t checked the code of the plugin and of draw io to know which one is increminated

build the diagram in draw io work fine , I have different objects in grafana after that,
 but I want to use cloudcraft 3d diagram that import only as one object.

is there a svg converter to drawio ?
If the point of view of Drawio is that they don t care the svg import .... I m not sure to succeed

**Comment by algenty** [comment]
Can you export your cloudcraft in visio format (vsd), not svg.
If you can, import visio into draw.io

**Comment by kyrianae** [comment]
Since last time I found a page where it was written that svg was import as only one object.
> then I wonder why svg generated from drawio with only 3 shapse is imported as 3 objects
nevertheless I understand the choice to not improve the svg integration

for vsd I will check the conversion but if i follow you others comments, drawio is not a svg editor nether a vsd one I think ?
cloudcraft have only 2d export to drawio, and 3d export to svg, no svg

but i will check vsd

**Comment by CrashLaker** [comment]
Hi @kyrianae,

The SVG will only be a single (root) one comprising many SVG shapes.
As you can see [here](https://www.w3schools.com/graphics/svg_rect.asp) there are paths, rectangles, circles, polygons , etc.

Draw.io uses mxGraph syntax so you'd have to manually convert SVG to mxGraph or via a Library that already does it. As of now
I'm also still looking for that library.

Few resources that might help you:
* https://github.com/algenty/grafana-flowcharting/issues/144#issuecomment-612511120 Manually converting SVG path to mxGraph <line>
* https://github.com/algenty/grafana-flowcharting/issues/87#issuecomment-623847354 Library to convert graphviz to draw.io
* https://github.com/algenty/grafana-flowcharting/issues/227 It's also possible to "manually programatically" create your mxGraph xml. This example was fairly easy since I only had to use <Rectangles>. In your example is a lot more complicated though.

regards,
C.

**Comment by CrashLaker** [comment]
Btw how is cloudcraft compared to using Draw.io?
I've never used CloudCraft but I've done some similar experiments on https://github.com/algenty/grafana-flowcharting/issues/148
Another interesting challenge would be to dinamically rearrange the layout like https://github.com/algenty/grafana-flowcharting/issues/145#issuecomment-615887352 
2D one https://github.com/algenty/grafana-flowcharting/issues/145#issuecomment-618382536

**Comment by kyrianae** [comment]
with cloudcraft you have price and so on of your platform
it s directly used to generate script to deploy the architecture 

Use the same graph for deploy architecture and monitor it  in grafana could be a very interesting thing
actually I want to minimize manual action and just want to use cots (We will see if we need to develop)
dirty plan b is to open svg from cloudcraft in drawio and add circle on area I want to change color and bind it with garfana data
maybe a little dev could automaize that.

thanks a lot @CrashLaker for all your informations and work

In parallel I checked if cloudcraft can export 3d graph in drawio

**Comment by kyrianae** [comment]
> Can you export your cloudcraft in visio format (vsd), not svg.
> If you can, import visio into draw.io

using visio, I loose a lot, color .....

**Comment by algenty** [comment]
export as visio and import into draw.io is olny the solution
