### ISSUE TITLE
Is project DEAD => Offcourse not, 1.0.0c in progress ;)

### ISSUE THREAD

**Issue by mirackle-spb** [algenty/grafana-flowcharting#331]
I just want to understand myself.
There is soo many people using it, but looks like noone supporting it.
Critical bug 283 it not fixed within year :(

**Comment by algenty** [comment]
My professional situation has changed and I no longer have time to devote as much time to it as before.
Have you try the beta version ? a new version is coming, at this time i don't fix current version

**Comment by chezgi** [comment]
dear algenty, i am glad that you are healthful.
this project was very good plugin.
 if anybody can maintain it, please inform us here.

**Comment by nc-ruth** [comment]
Hi @algenty,

Do you need help with administrating this project?
We are using this project for our needs, and the pile of issues is growing bigger and bigger.

Are you interested in letting others help maintain this project for you? 
We understand that your professional situation have changed, but it would be such a shame to block this project, due to you not having time to review/maintain this project.

What kind of ideas do you have with the project, and how do you see it survive in the long run?

**Comment by bijwaard** [comment]
Hi Arnaud,

A warm welcome back! Hope you are fine, except for the lack of time.

I tried to help out by answering some questions the past year, fortunately your latest snapshot is still working for most of us, even in the last grafana version.

Kind regards,
Dennis

**Comment by algenty** [comment]
Hi Denis,

Sorry for the long time. I debug the lastest version and upgrade with the lastest drawio, this is my plan

**Comment by algenty** [comment]
Offcource you 're help is welcome
I ll contact you soon

**Comment by CrashLaker** [comment]
Hi @algenty,

Glad you're doing well.
I'm willing to help too.
I don't have strong Angular knowledge but If you could guide us through your project file structure we might be able to slowly grap some bits and pieces. :)

regards,C.

**Comment by raphaelrrl** [comment]
Hi guys, I'm also willing to help, I use flowcharting a lot for Infrastructure Topologies for ISP internet service provider.

**Comment by algenty** [comment]
Please refer to #355
