### ISSUE TITLE
Presentation - Grafanacon or Monitorama

### ISSUE THREAD

**Issue by xkilian** [algenty/grafana-flowcharting#68]
Arnaud, 
You have created a very good plugin which is gaining in maturity. It might be time to present a use-case using the plugin at a conference. A flowcharting user(like @bijwaard)  and/or yourself could present a use-case, the roadmap, etc. This would publicize the plugin, how it works and aim at drumming up more developers and testers for the plugin. This plugins bridges a gap between a custom native UI(like @ryantxu has done at Natel Energy) and regular Grafana panels. It can be used in very imaginative ways(DCIM view, custom navigation page, SCADA type UI, Network maps, CI workflow, etc.), so it could make for very compelling presentation(s).

**Comment by algenty** [comment]
Hi 
it would be nice but my level of english is so bad, off course i give all rights to grafana team to present it, it's a great honor !! . When will the grafanacon take place ? @bijwaard (Dennis) has contributed a lot to the success of the plugin, maybe he can speak out.
I don't know, I am going to think about it.
At this time, i try to convert it with grafana_toolkit.

BR
Arnaud

**Comment by bijwaard** [comment]
Hi Arnaud and xkilian,
Thanks for the confidence, my English is much better than my French;-)
Since we don't have a big travel/conference budget, Monitorama 2020 in Portland would be tough. If next Grafanacon is closer to the Netherlands, I could present our flowcharting use case including the Energy dashboard, DSP data flow dashboard, and the basic steps to create such a dashboard with flowcharting. Additionally, I could prepare slides and/or give credentials to our live dashboards.
Kind regards,
Dennis

**Comment by xkilian** [comment]
I will see what interesting use we make of it and maybe will present it at a suitable conference. Keep up great work work.
