### ISSUE TITLE
Errors when using URL 

### ISSUE THREAD

**Issue by Seana36** [algenty/grafana-flowcharting#76]
Hello, 

I am using version 5.0 and am trying to use a URL to fetch my XML. Currently is is returning an error 
"Failed to execute atob on windows". Is there any solution for this?  

![image](https://user-images.githubusercontent.com/11064014/68419814-f52fd280-0168-11ea-85a0-a2d854bd5977.png)

![image](https://user-images.githubusercontent.com/11064014/68419764-df221200-0168-11ea-93c6-839eb0079c18.png)

**Comment by algenty** [comment]
Hi Seana36

With another user, the same error. 
After talk with him, he writes the url with the editor.
Fisrt, open url in browser.
View source 
and copy the result in Source Content with Download source off.
If not work, it's because it's not the source of draw.

Save the xml or drawio in storage, not with the editor.
Also, In 0.5.0, there is a bug on load, try 0.6.0

BR
Arnaud

**Comment by Seana36** [comment]
Hi Arnaud, 

I tried what you suggested and am still seeing the same "atob" error i mentioned before. I also tried to open it with the Edit Draw button but am getting document is blank error. I should also mention that in my url i will need to use a variable dynamically. 

![image](https://user-images.githubusercontent.com/11064014/68884454-3bdd7980-06e1-11ea-9f44-75ceca0d760b.png)

**Comment by algenty** [comment]
Can you try last version 0.6.0, please

**Comment by Seana36** [comment]
All issues were fixed when switching to 0.6.0 version. Thank you for all the help! Any idea when this will be moved to master branch?

**Comment by algenty** [comment]
today :)
