### ISSUE TITLE
Link with repeat templating variable

### ISSUE THREAD

**Issue by BilouteMaif** [algenty/grafana-flowcharting#98]
Hi,

I use a templating variable to list all my applications.
Next i repeat a template panel with my application variable. (My templating variable is multi value with "all" option)

When I use my application variable in a link url inside a rule, the $application variable doesn't work.
The link url keeps the global variable and not the repeat variable.
So my link is not dynamic depending on the application

Is there a subtlety or is this a feature that is not implemented yet?

Thks !

**Comment by algenty** [comment]
Variable are supported in 0.6.0, can you try it ?

**Comment by BilouteMaif** [comment]
Great thank You!
I will try when it will be on grafana release!
I tell you what :)

**Comment by IVBB** [comment]
Hi Algenty!

Currently I'm using 0.6.1 of Flowcharting Plugin. 

My problem is really similar to BilouteMaif's one. I'm trying to set a link with a template variable and set that variable to "All", but the link gets the value of All instead of any of the values it should be.

Finishing, I would like to congrat your team for the great job you've done.

Thank You!!!
